# Generated by Django 4.2.7 on 2025-08-05 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('beneficios', models.TextField(blank=True)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'Pessoa Jurídica'), ('temporario', 'Temporário'), ('estagio', 'Estágio'), ('freelancer', 'Freelancer'), ('terceirizado', 'Terceirizado')], max_length=15)),
                ('jornada_trabalho', models.CharField(choices=[('integral', 'Tempo Integral'), ('meio_periodo', 'Meio Período'), ('flexivel', 'Flexível'), ('escala', 'Escala')], max_length=15)),
                ('local_trabalho', models.CharField(max_length=200)),
                ('aceita_remoto', models.BooleanField(default=False)),
                ('requer_viagem', models.BooleanField(default=False)),
                ('area', models.CharField(max_length=100)),
                ('nivel_experiencia', models.CharField(choices=[('estagiario', 'Estagiário'), ('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior'), ('especialista', 'Especialista')], max_length=50)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('encerrada', 'Encerrada'), ('preenchida', 'Preenchida')], default='ativa', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(limit_choices_to={'tipo_usuario': 'empresa'}, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('escolaridade', 'Escolaridade'), ('experiencia', 'Experiência'), ('habilidade', 'Habilidade'), ('idioma', 'Idioma'), ('certificacao', 'Certificação'), ('habilitacao', 'Habilitação')], max_length=15)),
                ('descricao', models.CharField(max_length=200)),
                ('nivel_importancia', models.CharField(choices=[('obrigatorio', 'Obrigatório'), ('desejavel', 'Desejável'), ('diferencial', 'Diferencial')], max_length=15)),
                ('peso', models.IntegerField(default=1, help_text='Peso para o sistema de matching (1-10)')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_detalhados', to='vagas.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='CandidaturaVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('candidatado', 'Candidatado'), ('em_analise', 'Em Análise'), ('pre_selecionado', 'Pré-selecionado'), ('entrevista', 'Entrevista'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('desistiu', 'Desistiu')], default='candidatado', max_length=20)),
                ('score_compatibilidade', models.FloatField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('trabalhador', models.ForeignKey(limit_choices_to={'tipo_usuario': 'trabalhador'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='vagas.vaga')),
            ],
            options={
                'ordering': ['-score_compatibilidade', '-data_candidatura'],
                'unique_together': {('vaga', 'trabalhador')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_geral', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('nota_experiencia', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('nota_habilidades', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('nota_perfil', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentarios', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='vagas.candidaturavaga')),
            ],
        ),
    ]
