# Generated by Django 4.2.7 on 2025-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='data_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaga',
            name='escolaridade_minima',
            field=models.CharField(blank=True, choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Ensino Técnico'), ('superior', 'Ensino Superior'), ('pos_graduacao', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=50),
        ),
        migrations.AddField(
            model_name='vaga',
            name='experiencia_minima',
            field=models.PositiveIntegerField(default=0, help_text='Experiência mínima em anos'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='numero_vagas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
