# Generated by Django 5.2.18 on 2026-10-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="aceitou_termos_em",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="aceitou os termos em"
            ),
        ),
    ]
