# Generated by Django 5.2.18 on 2026-10-08 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(max_length=80)),
                ("area", models.CharField(max_length=60, verbose_name="área")),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="o que vai fazer"),
                ),
                (
                    "salario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vazio = a combinar.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "contrato",
                    models.CharField(
                        choices=[
                            ("clt", "CLT"),
                            ("temporario", "Temporário"),
                            ("diarista", "Diarista"),
                            ("estagio", "Estágio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "horario",
                    models.CharField(
                        choices=[
                            ("manha", "Manhã"),
                            ("tarde", "Tarde"),
                            ("noite", "Noite"),
                            ("integral", "Integral"),
                            ("escala", "Escala"),
                        ],
                        max_length=10,
                        verbose_name="horário",
                    ),
                ),
                ("bairro", models.CharField(max_length=80)),
                ("quantidade", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando aprovação"),
                            ("aprovada", "Aprovada"),
                            ("recusada", "Recusada"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("avaliada_em", models.DateTimeField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "avaliada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criada_em"],
                "permissions": [("aprovar_vaga", "Pode aprovar ou recusar vagas")],
            },
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interesses",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vaga", "candidato"), name="interesse_unico"
                    )
                ],
            },
        ),
    ]
