# Generated by Django 5.2.18 on 2026-10-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="motivo_recusa",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="motivo da recusa"
            ),
        ),
    ]
