# Generated by Django 4.2.7 on 2025-08-13 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vagas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_candidatos', models.IntegerField()),
                ('candidatos_compatíveis', models.IntegerField()),
                ('score_medio', models.FloatField()),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('parametros_utilizados', models.JSONField(default=dict)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.FloatField()),
                ('score_experiencia', models.FloatField()),
                ('score_habilidades', models.FloatField()),
                ('score_escolaridade', models.FloatField()),
                ('score_localizacao', models.FloatField()),
                ('score_salario', models.FloatField()),
                ('detalhes_matching', models.JSONField(default=dict)),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
                ('trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='vagas.vaga')),
            ],
            options={
                'ordering': ['-score_total'],
                'unique_together': {('vaga', 'trabalhador')},
            },
        ),
    ]
