# Generated by Django 4.2.7 on 2025-08-05 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.TextField()),
                ('resumo_profissional', models.TextField()),
                ('pretensao_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidade_viagem', models.BooleanField(default=False)),
                ('disponibilidade_mudanca', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('trabalhador', models.OneToOneField(limit_choices_to={'tipo_usuario': 'trabalhador'}, on_delete=django.db.models.deletion.CASCADE, related_name='curriculo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVagaProcurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_interesse', models.TextField(help_text='Áreas de interesse separadas por vírgula')),
                ('cargos_interesse', models.TextField(help_text='Cargos de interesse separados por vírgula')),
                ('tipo_contrato', models.CharField(choices=[('clt', 'CLT'), ('pj', 'Pessoa Jurídica'), ('temporario', 'Temporário'), ('estagio', 'Estágio'), ('freelancer', 'Freelancer'), ('terceirizado', 'Terceirizado')], max_length=15)),
                ('jornada_trabalho', models.CharField(choices=[('integral', 'Tempo Integral'), ('meio_periodo', 'Meio Período'), ('flexivel', 'Flexível'), ('escala', 'Escala')], max_length=15)),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aceita_viagem', models.BooleanField(default=False)),
                ('aceita_mudanca', models.BooleanField(default=False)),
                ('curriculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_vaga_procurada', to='curriculos.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=50)),
                ('nivel_leitura', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente'), ('nativo', 'Nativo')], max_length=15)),
                ('nivel_escrita', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente'), ('nativo', 'Nativo')], max_length=15)),
                ('nivel_conversacao', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('fluente', 'Fluente'), ('nativo', 'Nativo')], max_length=15)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='curriculos.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('especialista', 'Especialista')], max_length=15)),
                ('descricao', models.TextField(blank=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='curriculos.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('emprego_atual', models.BooleanField(default=False)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='curriculos.curriculo')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('fundamental_incompleto', 'Ensino Fundamental Incompleto'), ('fundamental_completo', 'Ensino Fundamental Completo'), ('medio_incompleto', 'Ensino Médio Incompleto'), ('medio_completo', 'Ensino Médio Completo'), ('tecnico', 'Técnico'), ('superior_incompleto', 'Superior Incompleto'), ('superior_completo', 'Superior Completo'), ('pos_graduacao', 'Pós-graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=25)),
                ('instituicao', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=200)),
                ('ano_inicio', models.IntegerField()),
                ('ano_conclusao', models.IntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('cursando', 'Cursando'), ('concluido', 'Concluído'), ('trancado', 'Trancado'), ('abandonado', 'Abandonado')], max_length=20)),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolaridades', to='curriculos.curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('carga_horaria', models.IntegerField()),
                ('data_conclusao', models.DateField()),
                ('certificado', models.FileField(blank=True, upload_to='certificados/')),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='curriculos.curriculo')),
            ],
        ),
    ]
