# Generated by Django 5.2.18 on 2026-10-08 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_nascimento", models.DateField()),
                ("bairro", models.CharField(max_length=80)),
                (
                    "escolaridade",
                    models.CharField(
                        choices=[
                            ("nenhuma", "Não estudei"),
                            ("fundamental", "Fundamental"),
                            ("medio", "Médio"),
                            ("tecnico", "Técnico"),
                            ("superior", "Superior"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "areas_interesse",
                    models.JSONField(
                        default=list,
                        help_text="Até 3, texto livre.",
                        verbose_name="áreas de interesse",
                    ),
                ),
                ("tem_cnh", models.BooleanField(default=False, verbose_name="tem CNH")),
                (
                    "categoria_cnh",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="categoria da CNH"
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "currículo",
            },
        ),
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "o_que_fazia",
                    models.CharField(max_length=120, verbose_name="o que fazia"),
                ),
                ("onde", models.CharField(max_length=120)),
                (
                    "quanto_tempo",
                    models.CharField(max_length=40, verbose_name="quanto tempo"),
                ),
                (
                    "curriculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencias",
                        to="curriculos.curriculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "experiência",
            },
        ),
    ]
